name: unit tests

on:
  push:
      branches: [ master ]
      paths:
      - 'oresat_linux_updater/**'
      - 'tests/**'
      - '.github/workflows/unit_tests.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'oresat_linux_updater/**'
      - 'tests/**'
      - '.github/workflows/unit_tests.yml'


jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        sudo apt-get install python3-pydbus python3-gi python3-pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run unit tests
      run: |
        # run as module, so it run with python version above (otherwise it uses 3.6)
        sudo python -m pytest tests/
